// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8azjDdadT6trQKXgTUJJpowi48rXEms',
    appId: '1:674971988389:web:2bb8ccf521e69c95e4384c',
    messagingSenderId: '674971988389',
    projectId: 'automeddispenser',
    authDomain: 'automeddispenser.firebaseapp.com',
    storageBucket: 'automeddispenser.appspot.com',
    measurementId: 'G-BG815W5V4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYe24yMadjFKXnWRsl-mliuSmGHV7E1xA',
    appId: '1:674971988389:android:2617ce72ce30dea0e4384c',
    messagingSenderId: '674971988389',
    projectId: 'automeddispenser',
    storageBucket: 'automeddispenser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71PdDZBtCpBcwsXsz2n4_9REKCzBg3Ok',
    appId: '1:674971988389:ios:33cff104b2ce2e0ee4384c',
    messagingSenderId: '674971988389',
    projectId: 'automeddispenser',
    storageBucket: 'automeddispenser.appspot.com',
    iosBundleId: 'com.example.doctorPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71PdDZBtCpBcwsXsz2n4_9REKCzBg3Ok',
    appId: '1:674971988389:ios:33cff104b2ce2e0ee4384c',
    messagingSenderId: '674971988389',
    projectId: 'automeddispenser',
    storageBucket: 'automeddispenser.appspot.com',
    iosBundleId: 'com.example.doctorPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT8azjDdadT6trQKXgTUJJpowi48rXEms',
    appId: '1:674971988389:web:e5ba024c791cf46fe4384c',
    messagingSenderId: '674971988389',
    projectId: 'automeddispenser',
    authDomain: 'automeddispenser.firebaseapp.com',
    storageBucket: 'automeddispenser.appspot.com',
    measurementId: 'G-SL5FY248JY',
  );

}